spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud

  data:
    rest:
      base-path: /data-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000"
          jwk-set-uri: "http://localhost:9000/oauth2/jwks"

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
